const express = require('express')

const router = express.Router()
const controller = require('../controller/character')
const { tryCatch } = require("../utils/tryCatch")

// get all characters
router.get('/', tryCatch(
  // #swagger.tags = ['Character']
  // #swagger.description = 'Displays all characters.'
  /* #swagger.responses[200] = { 
            description: 'Returns all characters information in a collection from mongodb genshin database',
            schema: { $ref: "#/definitions/Character collection" }
       } */
  controller.getAll
))

// get one character
router.get('/:id', tryCatch(
  // #swagger.tags = ['Character']
  // #swagger.description = 'Fetching a character document through _id from mongodb collection.'
  // #swagger.parameters['id'] = { description: 'ID of character.' }
  /* #swagger.responses[200] = { 
       schema: { $ref: "#/definitions/Character document" },
       description: 'Character data fetched from collection in db.' 
} */
  controller.getOne))

// add one
router.post('/', tryCatch(
  // #swagger.tags = ['Character']
  // #swagger.description = 'Create a new character document in the collection.'
  /* #swagger.parameters['character'] = {
               in: 'body',
               description: 'Information of a character to be created. All fields are required. Rarity must be 4star or 5star',
               required: true,
               schema: { $ref: "#/definitions/Character document creation" }
        } */
  /* #swagger.responses[201] = { 
           description: 'Returns character "_id" autogenerated by mongodb',
           schema: "63dd79bed4238c841b2794ee"
  } */
  controller.addOne))

// update one
router.put('/:id', controller.updateOne)
// delete one
router.delete('/:id', controller.delOne)

module.exports = router